kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster-101
networking:
  ipFamily: ipv4
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "iptables"
nodes:
- role: control-plane